FROM node:20-alpine AS portfolio-frontend
WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install
COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=portfolio-frontend /app/dist /usr/share/nginx/html

# Copy our custom Nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]